# Data Wrangling: Clean, Transform, Merge, Reshape
## Combining and Merging Data Sets
- pandas.merge : connects rows in DataFrames based on one or more keys (SQL *join*)
- pandas.concat : glues or stacks together objects along an axis
- combine_first : enables slicing together overlapping data to fill in missing values in one object with values from values

### Database-style DataFrame Merges
*merge* or *join* : combine data sets by linking rows using one or more *keys*

In [1]:
import pandas as pd
from pandas import DataFrame, Series
import numpy as np

In [2]:
df1 = DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                'data1': range(7)})
df1

data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   a
6      6   b

In [3]:
df2 = DataFrame({'key': ['a', 'b', 'd'],
                'data2': range(3)})
df2

data2 key
0      0   a
1      1   b
2      2   d

In [4]:
pd.merge(df1, df2)

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

In [5]:
pd.merge(df1, df2, on='key')

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

In [6]:
df3 = DataFrame({'lkey': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                 'data1': range(7)})
df4 = DataFrame({'rkey': ['a', 'b', 'd'],
                 'data2': range(3)})

In [7]:
df3

data1 lkey
0      0    b
1      1    b
2      2    a
3      3    c
4      4    a
5      5    a
6      6    b

In [8]:
df4

data2 rkey
0      0    a
1      1    b
2      2    d

In [9]:
pd.merge(df3, df4, left_on='lkey', right_on='rkey')

data1 lkey  data2 rkey
0      0    b      1    b
1      1    b      1    b
2      6    b      1    b
3      2    a      0    a
4      4    a      0    a
5      5    a      0    a

In [10]:
# how = 'outer'
pd.merge(df1, df2, how='outer')  # default : inner

data1 key  data2
0    0.0   b    1.0
1    1.0   b    1.0
2    6.0   b    1.0
3    2.0   a    0.0
4    4.0   a    0.0
5    5.0   a    0.0
6    3.0   c    NaN
7    NaN   d    2.0

In [11]:
df1 = DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                'data1': range(6)})
df2 = DataFrame({'key': ['a', 'b', 'a', 'b', 'd'],
                'data2': range(5)})

In [12]:
df1

data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   b

In [13]:
df2

data2 key
0      0   a
1      1   b
2      2   a
3      3   b
4      4   d

In [14]:
pd.merge(df1, df2, how='left')

data1 key  data2
0       0   b    1.0
1       0   b    3.0
2       1   b    1.0
3       1   b    3.0
4       2   a    0.0
5       2   a    2.0
6       3   c    NaN
7       4   a    0.0
8       4   a    2.0
9       5   b    1.0
10      5   b    3.0

In [15]:
# To merge with multiple keys
left = DataFrame({'key1': ['foo', 'foo', 'bar'],
                  'key2': ['one', 'two', 'one'],
                  'lval': [1, 2, 3]})
right = DataFrame({'key1': ['foo', 'foo', 'bar', 'bar'],
                   'key2': ['one', 'one', 'one', 'two'],
                   'rval': [4, 5, 6, 7]})
pd.merge(left, right, on=['key1', 'key2'], how='outer')

key1 key2  lval  rval
0  foo  one   1.0   4.0
1  foo  one   1.0   5.0
2  foo  two   2.0   NaN
3  bar  one   3.0   6.0
4  bar  two   NaN   7.0

In [16]:
# overlapping column names
pd.merge(left, right, on='key1')

key1 key2_x  lval key2_y  rval
0  foo    one     1    one     4
1  foo    one     1    one     5
2  foo    two     2    one     4
3  foo    two     2    one     5
4  bar    one     3    one     6
5  bar    one     3    two     7

In [17]:
pd.merge(left, right, on='key1', suffixes=('_left', '_right'))

key1 key2_left  lval key2_right  rval
0  foo       one     1        one     4
1  foo       one     1        one     5
2  foo       two     2        one     4
3  foo       two     2        one     5
4  bar       one     3        one     6
5  bar       one     3        two     7

*merge function arguments*

|Argument|Description|
|---------|--------------|
|left||
|right||
|how|**'inner'**, 'outer', 'left', 'right'|
|on||
|left_on||
|right_on||
|left_index||
|right_index||
|sort||
|suffixes||
|copy||

### Merging on Index

In [18]:
left1 = DataFrame({'key': ['a', 'b', 'a', 'a', 'b', 'c'],
                  'value': range(6)})
right1 = DataFrame({'group_val': [3.5, 7]}, index=['a','b'])

In [19]:
left1

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [20]:
right1

group_val
a        3.5
b        7.0

In [21]:
# left_index=True, right_index=True
pd.merge(left1, right1, left_on='key', right_index=True)

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

In [22]:
pd.merge(left1, right1, left_on='key', right_index=True, how='outer')

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

In [23]:
# Hierachically-indexed data
lefth = DataFrame({'key1': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
                  'key2': [2000, 2001, 2002, 2001, 2002],
                  'data': np.arange(5.)})

righth = DataFrame(np.arange(12).reshape((6, 2)),
                  index=[['Nevada', 'Nevada', 'Ohio', 'Ohio', 'Ohio', 'Ohio'],
                         [2001, 2000, 2000, 2000, 2001, 2002]],
                  columns=['envent1', 'event2'])

In [24]:
lefth

data    key1  key2
0   0.0    Ohio  2000
1   1.0    Ohio  2001
2   2.0    Ohio  2002
3   3.0  Nevada  2001
4   4.0  Nevada  2002

In [25]:
righth

envent1  event2
Nevada 2001        0       1
       2000        2       3
Ohio   2000        4       5
       2000        6       7
       2001        8       9
       2002       10      11

In [26]:
pd.merge(lefth, righth, left_on=['key1', 'key2'], right_index=True)

data    key1  key2  envent1  event2
0   0.0    Ohio  2000        4       5
0   0.0    Ohio  2000        6       7
1   1.0    Ohio  2001        8       9
2   2.0    Ohio  2002       10      11
3   3.0  Nevada  2001        0       1

In [27]:
pd.merge(lefth, righth, left_on=['key1', 'key2'], right_index=True, how='outer')

data    key1  key2  envent1  event2
0   0.0    Ohio  2000      4.0     5.0
0   0.0    Ohio  2000      6.0     7.0
1   1.0    Ohio  2001      8.0     9.0
2   2.0    Ohio  2002     10.0    11.0
3   3.0  Nevada  2001      0.0     1.0
4   4.0  Nevada  2002      NaN     NaN
4   NaN  Nevada  2000      2.0     3.0

In [28]:
# Using the indexes of both sides
left2 = DataFrame([[1., 2.], [3., 4.], [5., 6.]], index=['a', 'c', 'e'],
                  columns=['Ohio', 'Nevada'])
right2 = DataFrame([[7., 8.], [9., 10.], [11., 12.], [13, 14]],
                   index=['b', 'c', 'd', 'e'], columns=['Missouri', 'Alabama'])

In [29]:
left2

Ohio  Nevada
a   1.0     2.0
c   3.0     4.0
e   5.0     6.0

In [30]:
right2

Missouri  Alabama
b       7.0      8.0
c       9.0     10.0
d      11.0     12.0
e      13.0     14.0

In [31]:
pd.merge(left2, right2, how='outer', left_index=True, right_index=True)

Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

In [32]:
# join() : for merging by index
left2.join(right2, how='outer')

Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

In [33]:
# also supports joining the index of the passed DataFrame on one of the columns of the calling DataFrame
left1.join(right1, on='key')

key  value  group_val
0   a      0        3.5
1   b      1        7.0
2   a      2        3.5
3   a      3        3.5
4   b      4        7.0
5   c      5        NaN

In [34]:
# for simple index-on-index merges
another = DataFrame([[7., 8.], [9., 10.], [11., 12.], [16., 17.]],
                    index=['a', 'c', 'e', 'f'], columns=['New York', 'Oregon'])

In [35]:
left2.join([right2, another])

Ohio  Nevada  Missouri  Alabama  New York  Oregon
a   1.0     2.0       NaN      NaN       7.0     8.0
c   3.0     4.0       9.0     10.0       9.0    10.0
e   5.0     6.0      13.0     14.0      11.0    12.0

In [36]:
left2.join([right2, another], how='outer')

Ohio  Nevada  Missouri  Alabama  New York  Oregon
a   1.0     2.0       NaN      NaN       7.0     8.0
b   NaN     NaN       7.0      8.0       NaN     NaN
c   3.0     4.0       9.0     10.0       9.0    10.0
d   NaN     NaN      11.0     12.0       NaN     NaN
e   5.0     6.0      13.0     14.0      11.0    12.0
f   NaN     NaN       NaN      NaN      16.0    17.0

### Concatenating Along an Axis

In [37]:
# Numpy : concatenate()
arr = np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
np.concatenate([arr, arr], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [39]:
s1 = Series([0, 1], index=['a', 'b'])
s2 = Series([2, 3, 4], index=['c', 'd', 'e'])
s3 = Series([5, 6], index=['f', 'g'])

In [40]:
pd.concat([s1, s2, s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [41]:
# if axis = 1,
pd.concat([s1, s2, s3], axis=1)

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

*concat function argumennts*

|Argument|Description|
|--------|------------|
|objs||
|axis||
|join||
|join_axes||
|keys||
|levels||
|names||
|verify_integrity||
|ignore_index||

### Combining Data with Overlap

In [42]:
# Numpy's where
a = Series([np.nan, 2.5, np.nan, 3.5, 4.5, np.nan],
           index=['f', 'e', 'd', 'c', 'b', 'a'])
b = Series(np.arange(len(a), dtype=np.float64),
           index=['f', 'e', 'd', 'c', 'b', 'a'])
b[-1] = np.nan

In [43]:
a

f    NaN
e    2.5
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

In [44]:
b

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    NaN
dtype: float64

In [45]:
np.where(pd.isnull(a), b, a)

array([ 0. ,  2.5,  2. ,  3.5,  4.5,  nan])

In [46]:
# combine_first() : "patching" missing data

In [47]:
b[:-2].combine_first(a[2:])

a    NaN
b    4.5
c    3.0
d    2.0
e    1.0
f    0.0
dtype: float64

In [48]:
df1 = DataFrame({'a': [1., np.nan, 5., np.nan],
                 'b': [np.nan, 2., np.nan, 6.],
                 'c': range(2, 18, 4)})

df2 = DataFrame({'a': [5., 4., np.nan, 3., 7.],
                 'b': [np.nan, 3., 4., 6., 8.]})

In [49]:
df1

a    b   c
0  1.0  NaN   2
1  NaN  2.0   6
2  5.0  NaN  10
3  NaN  6.0  14

In [50]:
df2

a    b
0  5.0  NaN
1  4.0  3.0
2  NaN  4.0
3  3.0  6.0
4  7.0  8.0

In [51]:
df1.combine_first(df2)

a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN

## Reshaping and Pivoting
### Reshaping with Hierarchical Indexing
- **stack**: this "rotates" or pivots from the columns in the data to the rows
- **unstack**: this pivots from the rows into the columns

In [52]:
data = DataFrame(np.arange(6).reshape((2, 3)),
                 index=pd.Index(['Ohio', 'Colorado'], name='state'),
                 columns=pd.Index(['one', 'two', 'three'], name='number'))
data

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [53]:
# stack()
result = data.stack()
result

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int64

In [54]:
# unstack()
result.unstack()

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [55]:
# unstack a diffrerent level - by default the innermost level is unstacked
result.unstack(0)

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

In [56]:
result.unstack('state')

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

In [57]:
s1 = Series([0, 1, 2, 3], index=['a', 'b', 'c', 'd'])
s2 = Series([4, 5, 6], index=['c', 'd', 'e'])
data2 = pd.concat([s1, s2], keys=['one', 'two'])
data2.unstack()

a    b    c    d    e
one  0.0  1.0  2.0  3.0  NaN
two  NaN  NaN  4.0  5.0  6.0

In [58]:
data2.unstack().stack()

one  a    0.0
     b    1.0
     c    2.0
     d    3.0
two  c    4.0
     d    5.0
     e    6.0
dtype: float64

In [59]:
data2.unstack().stack(dropna=False)

one  a    0.0
     b    1.0
     c    2.0
     d    3.0
     e    NaN
two  a    NaN
     b    NaN
     c    4.0
     d    5.0
     e    6.0
dtype: float64

In [60]:
# When unstacking in a DataFrame, the level unstacked becomes the lowest level in the result
df = DataFrame({'left': result, 'right': result + 5},
               columns=pd.Index(['left', 'right'], name='side'))
df

side             left  right
state    number             
Ohio     one        0      5
         two        1      6
         three      2      7
Colorado one        3      8
         two        4      9
         three      5     10

In [61]:
df.unstack('state')

side   left          right         
state  Ohio Colorado  Ohio Colorado
number                             
one       0        3     5        8
two       1        4     6        9
three     2        5     7       10

In [62]:
df.unstack('state').stack('side')

state         Ohio  Colorado
number side                 
one    left      0         3
       right     5         8
two    left      1         4
       right     6         9
three  left      2         5
       right     7        10

## Data Transformation
### Removing Duplicates

In [63]:
data = DataFrame({'k1': ['one'] * 3 + ['two'] * 4,
                  'k2': [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  one   1
2  one   2
3  two   3
4  two   3
5  two   4
6  two   4

In [64]:
# duplicated()
data.duplicated()

0    False
1     True
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [65]:
# drop_duplicated()
data.drop_duplicates()

k1  k2
0  one   1
2  one   2
3  two   3
5  two   4

In [66]:
# filter duplicates only based on the 'k1' columns
data['v1'] = range(7)
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
3  two   3   3

In [67]:
# keep='last' (python 2.x : take_last=True)
data.drop_duplicates(['k1', 'k2'], keep='last')

k1  k2  v1
1  one   1   1
2  one   2   2
4  two   3   4
6  two   4   6

### Transforming Data Using a Functional or Mapping

In [68]:
data = DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'Pastrami',
                           'corned beef', 'Bacon', 'pastrami', 'honey ham',
                           'nova lox'],
                  'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [69]:
# add a columnb indicating the type of animal that each food came from
meat_to_animal = {
    'bacon': 'pig',
    'pulled pork': 'pig',
    'pastrami': 'cow',
    'corned beef': 'cow',
    'honey ham': 'pig',
    'nova lox': 'salmom'
}

In [70]:
data['animal'] = data['food'].map(str.lower).map(meat_to_animal)
                                                 
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmom

In [71]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmom
Name: food, dtype: object

### Replacing Values

In [72]:
data = Series([1., -999., 2., -999., -1000., 3.])

data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [73]:
# replace -999 to NA
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [74]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [75]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [76]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

### Renaming Axis Indexes

In [77]:
data = DataFrame(np.arange(12).reshape((3, 4)),
                 index=['Ohio', 'Colorado', 'New York'],
                 columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [78]:
data.index.map(str.upper)

array(['OHIO', 'COLORADO', 'NEW YORK'], dtype=object)

In [79]:
data.index = data.index.map(str.upper)

In [80]:
data

one  two  three  four
OHIO        0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

In [81]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [82]:
data.rename(index={'OHIO': 'INDIANA'},
            columns={'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA     0    1         2     3
COLORADO    4    5         6     7
NEW YORK    8    9        10    11

In [83]:
# inplace=True
_ = data.rename(index={'OHIO': 'INDIANA'}, inplace=True)

In [84]:
data

one  two  three  four
INDIANA     0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

### Discretization and Binning

In [85]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]

In [86]:
cats = pd.cut(ages, bins)

cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, object): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [87]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [88]:
cats.categories

Index(['(18, 25]', '(25, 35]', '(35, 60]', '(60, 100]'], dtype='object')

In [89]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [90]:
# () : open, [] : closed
# right=False
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, object): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [91]:
group_names = ['Youth', 'YoungAdult', 'MiddleAges', 'Senior']

In [92]:
pd.cut(ages, bins, labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAges, MiddleAges, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAges < Senior]

In [93]:
data = np.random.rand(20)
pd.cut(data, 4, precision=2)

[(0.42, 0.61], (0.42, 0.61], (0.61, 0.81], (0.61, 0.81], (0.02, 0.22], ..., (0.42, 0.61], (0.61, 0.81], (0.22, 0.42], (0.02, 0.22], (0.61, 0.81]]
Length: 20
Categories (4, object): [(0.02, 0.22] < (0.22, 0.42] < (0.42, 0.61] < (0.61, 0.81]]

In [94]:
# qcut : bins the data based on sample quantiles
data = np.random.randn(1000)
cats = pd.qcut(data, 4)

cats

[(-0.714, -0.0346], (0.686, 3.682], (0.686, 3.682], (-0.0346, 0.686], (-0.714, -0.0346], ..., [-2.862, -0.714], (0.686, 3.682], [-2.862, -0.714], [-2.862, -0.714], [-2.862, -0.714]]
Length: 1000
Categories (4, object): [[-2.862, -0.714] < (-0.714, -0.0346] < (-0.0346, 0.686] < (0.686, 3.682]]

In [95]:
pd.value_counts(cats)

(0.686, 3.682]       250
(-0.0346, 0.686]     250
(-0.714, -0.0346]    250
[-2.862, -0.714]     250
dtype: int64

In [96]:
# your own quantiles(numbers between 0 and 1)
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])

[(-1.341, -0.0346], (-0.0346, 1.255], (-0.0346, 1.255], (-0.0346, 1.255], (-1.341, -0.0346], ..., [-2.862, -1.341], (1.255, 3.682], [-2.862, -1.341], (-1.341, -0.0346], (-1.341, -0.0346]]
Length: 1000
Categories (4, object): [[-2.862, -1.341] < (-1.341, -0.0346] < (-0.0346, 1.255] < (1.255, 3.682]]

### Detecting and Filtering Outliers

In [97]:
np.random.seed(12345)
data = DataFrame(np.random.randn(1000, 4))

In [98]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067684     0.067924     0.025598    -0.002298
std       0.998035     0.992106     1.006835     0.996794
min      -3.428254    -3.548824    -3.184377    -3.745356
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.366626     2.653656     3.260383     3.927528

In [99]:
col = data[3]
col[np.abs(col) > 3]

97     3.927528
305   -3.399312
400   -3.745356
Name: 3, dtype: float64

In [100]:
# to select all rows having a value exceeding 3 or -3
data[(np.abs(data) > 3).any(1)]    # 1 = 'columns'

0         1         2         3
5   -0.539741  0.476985  3.248944 -1.021228
97  -0.774363  0.552936  0.106061  3.927528
102 -0.655054 -0.565230  3.176873  0.959533
305 -2.315555  0.457246 -0.025907 -3.399312
324  0.050188  1.951312  3.260383  0.963301
400  0.146326  0.508391 -0.196713 -3.745356
499 -0.293333 -0.242459 -3.056990  1.918403
523 -3.428254 -0.296336 -0.439938 -0.867165
586  0.275144  1.179227 -3.184377  1.369891
808 -0.362528 -3.548824  1.553205 -2.186301
900  3.366626 -2.372214  0.851010  1.332846

In [101]:
# cap values outside the interval -3 to 3
data[np.abs(data) > 3] = np.sign(data) * 3    # sign() : -1 if x < 0, 0 if x==0, 1 if x > 0

In [102]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067623     0.068473     0.025153    -0.002081
std       0.995485     0.990253     1.003977     0.989736
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.000000     2.653656     3.000000     3.000000

### Permutation and Random Sampling

In [103]:
df = DataFrame(np.arange(5 * 4).reshape((5, 4)))

In [104]:
sampler = np.random.permutation(5)

In [105]:
sampler

array([1, 0, 2, 3, 4])

In [106]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [107]:
df.take(sampler)

0   1   2   3
1   4   5   6   7
0   0   1   2   3
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [108]:
#  random sampling with permutation
df.take(np.random.permutation(len(df))[:3])

0   1   2   3
1   4   5   6   7
3  12  13  14  15
4  16  17  18  19

In [109]:
bag = np.array([5, 7, -1, 6, 4])
sampler = np.random.randint(0, len(bag), size=10)

In [110]:
sampler

array([4, 4, 2, 2, 2, 0, 3, 0, 4, 1])

In [111]:
draws = bag.take(sampler)

draws

array([ 4,  4, -1, -1, -1,  5,  6,  5,  4,  7])

### Computing Indicator/Dummy Variables 

In [112]:
df = DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                'data1':range(6)})

In [113]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [114]:
dummies = pd.get_dummies(df['key'], prefix='key')

In [115]:
df_with_dummy = df[['data1']].join(dummies)

In [116]:
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [117]:
values = np.random.randn(10)
values

array([ 0.32496836,  0.20377461,  0.34886204,  0.51600937, -0.48982135,
       -0.6287463 ,  0.2664145 ,  1.0836849 ,  0.30334881, -1.1072385 ])

In [118]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]
pd.get_dummies(pd.cut(values, bins))

(0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1]
0         0           1           0           0         0
1         0           1           0           0         0
2         0           1           0           0         0
3         0           0           1           0         0
4         0           0           0           0         0
5         0           0           0           0         0
6         0           1           0           0         0
7         0           0           0           0         0
8         0           1           0           0         0
9         0           0           0           0         0

## String Manipulation
### String Object Methods

In [119]:
val = 'a, b, guido'
val.split(',')

['a', ' b', ' guido']

In [120]:
pieces = [x.strip() for x in val.split(',')]  # 'strip' - trim whitespace(include newlines)

In [121]:
pieces

['a', 'b', 'guido']

In [122]:
first, second, third = pieces

In [123]:
first + '::' + second + '::' + third

'a::b::guido'

In [124]:
'::'.join(pieces)

'a::b::guido'

In [125]:
'guido' in val

True

In [126]:
val.index(',')

1

In [127]:
val.find(':')
## index : exception, find : return -1

-1

In [128]:
# count
val.count(',')

2

In [129]:
# replace
val.replace(',', '::')

'a:: b:: guido'

In [130]:
val.replace(',', '')

'a b guido'

*Python built-in string methods*

|Argument|Description|
|--------|---------------|
|count||
|endswith, startswith||
|join||
|index||
|find||
|rfind||
|replace||
|strip, rstrip, lstrip||
|split||
|lower, upper||
|ljust, rjust||

------

↓↓

### Regular expressions

In [131]:
import re

In [132]:
text = "foo      bar\t baz  \tqux"
re.split('\s+', text)

['foo', 'bar', 'baz', 'qux']

In [133]:
# reusable regex object
regex = re.compile('\s+')

regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [134]:
regex.findall(text)

['      ', '\t ', '  \t']

In [135]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""

pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'

regex = re.compile(pattern, flags=re.IGNORECASE)

In [136]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [137]:
m = regex.search(text)  # search() returns a special match object for the first emaill address in the text

In [138]:
m

<_sre.SRE_Match object; span=(5, 20), match='dave@google.com'>

In [139]:
text[m.start():m.end()]

'dave@google.com'

In [140]:
print(regex.match(text))

None


In [141]:
print(regex.sub('REDACTED', text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED



In [142]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'

regex = re.compile(pattern, flags=re.IGNORECASE)

In [143]:
m = regex.match('wesm@bright.net')

m.groups()

('wesm', 'bright', 'net')

In [144]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [145]:
# \1, \2 ...
print(regex.sub(r'Username: \1, Domain: \2, Suffix: \3', text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com



In [146]:
regex = re.compile(r"""
    (?P<username>[A-Z0-9._%+-]+)
    @
    (?P<domain>[A-Z0-9.-]+)
    \.
    (?P<suffix>[A-Z]{2,4})""", flags=re.IGNORECASE|re.VERBOSE)

In [147]:
m = regex.match('wesm@bright.net')

m.groupdict()

{'domain': 'bright', 'suffix': 'net', 'username': 'wesm'}

*Regular expression methodS*

|Argument|Description|
|---------|------------|
|findall, finditer||
|match||
|search||
|split||
|sub, subn||

### Vectorized string functions in pandas

In [148]:
data = {'Dave': 'dave@google.com', 'Steve': 'steve@gmail.com',
        'Rob': 'rob@gmail.com', 'Wes': np.nan}
data = Series(data)

In [149]:
data

Dave     dave@google.com
Rob        rob@gmail.com
Steve    steve@gmail.com
Wes                  NaN
dtype: object

In [150]:
data.str.contains('gamil')

Dave     False
Rob      False
Steve    False
Wes        NaN
dtype: object

In [151]:
pattern

'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

In [152]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Rob        [(rob, gmail, com)]
Steve    [(steve, gmail, com)]
Wes                        NaN
dtype: object

In [153]:
matches = data.str.match(pattern, flags=re.IGNORECASE)

/anaconda/envs/tensorflow/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: In future versions of pandas, match will change to always return a bool indexer.
  """Entry point for launching an IPython kernel.


In [154]:
matches.str.get(1)

Dave     google
Rob       gmail
Steve     gmail
Wes         NaN
dtype: object

In [155]:
matches.str[0]

Dave      dave
Rob        rob
Steve    steve
Wes        NaN
dtype: object

In [156]:
data.str[:5]

Dave     dave@
Rob      rob@g
Steve    steve
Wes        NaN
dtype: object

*Vectorized string methods*

|Method|Description|
|------|--------------|
|cat||
|contains||
|count||
|endswith, startswith||
|findall||
|get||
|join||
|len||
|lower, upper||
|match||
|pad||
|center||
|repeat||
|replace||
|slice||
|split||
|strip, rstrip, lstrip||